### ISSUE TITLE
Support the SQL Server URL syntax

### ISSUE THREAD

**Issue by Gaff** [Azure/azure-sqldb-spark#13]
It's possible to encode various properties for SQL Server within a URL. For example databaseName, username, password. See: https://docs.microsoft.com/en-us/sql/connect/jdbc/building-the-connection-url?view=sql-server-2017

Would it be possible to support the same syntax in the `Config` objects?

Seems like there's a function to parse these URLs: 

    SQLServerDriver ssd = new SQLServerDriver();
    ssd.getPropertyInfo(jdbcUrl, new Properties());

**Comment by arvindshmicrosoft** [comment]
Thank you for your suggestion. The new [Apache Spark Connector for SQL Server and Azure SQL](https://github.com/microsoft/sql-spark-connector) does support the JDBC URL syntax. I recommend you take a look at that one and evaluate if it would meet your needs. There are no plans to address this request in this connector. Hence, closing.
