### ISSUE TITLE
Running Stored Proc using the library

### ISSUE THREAD

**Issue by kashishbest** [Azure/azure-sqldb-spark#16]
Hi,

We have a use case, where we need the results of a stored proc, in a dataframe, 

So I created a query, and tried using a custom query, but that did not work out.

Error: com.microsoft.sqlserver.jdbc.SQLServerException: "<argument-1>" is not a recognized table hints option. If it is intended as a parameter to a table-valued function or to the CHANGETABLE function, ensure that your database compatibility mode is set to 90.

Can someone help?

**Comment by bensonmve** [comment]
Could you copy-paste how you are calling it?

**Comment by bensonmve** [comment]
You need to put it between brackets and give an alias: `val customQuery = "(SELECT Col1, Col2 FROM Table) AS CustomTable"`

I have never tried with a stored procedure like this `val customQuery = "(EXEC myStoredProcedure) AS CustomTable"`

**Comment by wimlova** [comment]
Anybody knows how to call a SP using the spark connector? 
The above suggestion is not working:

Incorrect syntax near the keyword 'EXEC'.

**Comment by JasonHood** [comment]
//Specify the procedure to run as a string. 
val procquery = "stored_proc"

//Config Map which contains connection details, customquery, and driver.            
val ProcQueryConfig = Config(Map(
              "url"            -> url,
              //"instanceName"   -> InstanceName,
              //"portNumber"     -> PortNumber,
              "databaseName"   -> databaseName,
              //"dbTable"        -> dbTable,
              "user"           -> user, 
              "password"       -> password,
              "connectTimeout" -> "5",
              "queryTimeout"   -> "5",
              "queryCustom"  -> procquery,
              "driver" -> "com.microsoft.sqlserver.jdbc.SQLServerDriver"
            ));

//Call the query. Should follow SparkSession.sqlContext.sqlDBQuery(config) when using recent spark //versions.
sqlContext.sqlDBQuery(ProcQueryConfig);

**Comment by nitin24g** [comment]
@JasonHood - Any idea how I can pass parameter to the SP in the above code ?

**Comment by arvindshmicrosoft** [comment]
It would be easier to invoke stored procedures using regular JDBC driver based code. Closing this as it is not going to be addressed in the connector.
