### ISSUE TITLE
value sqlDb is not a member of org.apache.spark.sql.DataFrameReader

### ISSUE THREAD

**Issue by keyushah** [Azure/azure-sqldb-spark#21]
I get this error while running in databricks notebook. 

notebook:15: error: value sqlDb is not a member of org.apache.spark.sql.DataFrameReader
val collection = sqlContext.read.sqlDb(config)

I imported uber jar as library

**Comment by akuzhan** [comment]
Hi, 

I am facing same issue as well. Followed documentation, built jar file and uploaded it nevertheless I am having same issue. 

Could someone please look into it? Also it would be fantastic to add this library to maven, very unfortunate it is not there yet.

 error: value sqlDb is not a member of org.apache.spark.sql.DataFrameReader
val collection = sqlContext.read.sqlDb(config)

**Comment by akuzhan** [comment]
I just copied it from documentation, looks like it was failing due to case sensitivity in my case.

**Comment by SimonHStats** [comment]
I am also getting the same issue. Akuzhan - did you find a fix?

**Comment by rtuason** [comment]
I ran into this as well, and it seems that the documentation page at the [Microsoft docs site](https://docs.microsoft.com/en-us/azure/sql-database/sql-database-spark-connector) has incorrect casing, as @akuzhan mentioned. We can see [here](https://github.com/Azure/azure-sqldb-spark/blob/fa1cf19ed797648a20d9b7f474d7c2cd88829ada/src/main/scala/com/microsoft/azure/sqldb/spark/connect/DataFrameReaderFunctions.scala) that we have to use "sqlDB" with a capital 'B'

**Comment by agnaldocarmo** [comment]
> I ran into this as well, and it seems that the documentation page at the [Microsoft docs site](https://docs.microsoft.com/en-us/azure/sql-database/sql-database-spark-connector) has incorrect casing, as @akuzhan mentioned. We can see [here](https://github.com/Azure/azure-sqldb-spark/blob/fa1cf19ed797648a20d9b7f474d7c2cd88829ada/src/main/scala/com/microsoft/azure/sqldb/spark/connect/DataFrameReaderFunctions.scala) that we have to use "sqlDB" with a capital 'B'

Thanks is solved me a big issue

**Comment by gregl83** [comment]
Pull Request Opened: https://github.com/Azure/azure-sqldb-spark/pull/60

**Comment by arvindshmicrosoft** [comment]
Closing this Issue as the corresponding PR has been merged. Thank you @gregl83 for your contribution!
