### ISSUE TITLE
create external table with this driver

### ISSUE THREAD

**Issue by gbrueckl** [Azure/azure-sqldb-spark#22]
similar to creating external tables on top of JDBC (as described here https://docs.azuredatabricks.net/spark/latest/data-sources/sql-databases.html#spark-sql-example)
could this also be implemented using this driver?
would we expect a similar performance gain?

**Comment by arvindshmicrosoft** [comment]
Thank you @gbrueckl for your idea. Unfortunately I am not aware of prior work or testing that has happened to enable this. As you also probably know, this connector is not actively maintained. I suggest you post this idea to [the new repo](https://github.com/microsoft/sql-spark-connector) if you are still interested in the pattern.
