### ISSUE TITLE
Data source com.databricks.spark.sqldw does not support streamed writing

### ISSUE THREAD

**Issue by ManjunathGuntha** [Azure/azure-sqldb-spark#24]
In databricks, I am reading data from eventhub and trying to write Streaming data to SQL DW :

Df.writeStream
.format("com.databricks.spark.sqldw")
.option("url", s"")
.option("forwardSparkAzureStorageCredentials", "true")
.option("dbTable",  "< table name>")
.option("checkpointLocation", "checkpoint_location")
.start()
but i am getting the below error:
java.lang.UnsupportedOperationException: Data source com.databricks.spark.sqldw does not support streamed writing

Can you please look into this issue?

**Comment by arvindshmicrosoft** [comment]
Hi Manjunath, this is not the repo for the SQL DW connector (that is not open source). Your feedback is noted but as I mentioned that is a different connector. Sorry!
