### ISSUE TITLE
"IF EXISTS ()   BEGIN ;WITH" doesnt work 

### ISSUE THREAD

**Issue by pidugusundeep** [Azure/azure-sqldb-spark#25]
it always shows Incorrect syntax near the keyword 'IF'  is this actually supported ? or do i have to reframe the query ?

**Comment by arvindshmicrosoft** [comment]
Sorry this question does not have much details, and in any case, for executing regular T-SQL batches, it may be easier to directly call into JDBC code. See #16 for some possible hints. In any case this library is not actively maintained anymore, and hence I am closing this issue.
