### ISSUE TITLE
Use Spark Data Source API to implement sqldb

### ISSUE THREAD

**Issue by shanyu** [Azure/azure-sqldb-spark#26]
Hi,

Is there a plan to move to Data Source API instead of manually extending DataFrameReader/Writer?

E.g.:
https://github.com/apache/spark/blob/master/sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/jdbc/JdbcRelationProvider.scala

**Comment by arvindshmicrosoft** [comment]
Thank you for your questions and ideas. Consider evaluating the 
[Apache Spark Connector for SQL Server and Azure SQL](https://github.com/microsoft/sql-spark-connector) which is a newer connector.

I am closing this issue as there are no plans to address this request in this connector.
