### ISSUE TITLE
KeyStoreAuthentication does not support Azure KeyVault

### ISSUE THREAD

**Issue by benleroux** [Azure/azure-sqldb-spark#33]
I'm unable to specify AzureKeyVault for the KeyStoreAuthentication config.

This seems to only support Java Key Store but the underlying JDBC seems to support it. 

Trying to use Always Encrypted from Spark.

**Comment by arvindshmicrosoft** [comment]
@benleroux - I'm sorry but I don't have anything specific to add for your question. This project is not actively maintained. We are generally recommending users to consider the [newer one](https://github.com/microsoft/sql-spark-connector) which should work for more cases, and is more active than this repo.
