### ISSUE TITLE
Error: value azurePushdownQuery is not a member of org.apache.spark.sql.SparkSession

### ISSUE THREAD

**Issue by prapanw** [Azure/azure-sqldb-spark#34]
I get this error when trying to run a custom query based on the example mentioned here:
https://github.com/Azure/azure-sqldb-spark#pushdown-query-to-azure-sql-database-or-sql-server

This is my code:

```
import com.microsoft.azure.sqldb.spark.config.Config
import com.microsoft.azure.sqldb.spark.query._

val createTableQueryString = s"""
  IF NOT EXISTS (SELECT * FROM sysobjects WHERE name = 'cohorts_analysis_manifest' and xtype ='U')
      USE testDb;
      CREATE TABLE testTbl
      (
          id bigint,
          name [varchar](255),
          ingestdate [varchar](10)
          CONSTRAINT [PK_testDb_testTbl] PRIMARY KEY CLUSTERED
          (
                    ingestdate DESC,
                    id ASC
          ) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
      )
"""
val createTableConfig = Config(Map(
  "url"            -> "myTestDbServer.database.windows.net",
  "databaseName"   -> "testDb",
  "user"           -> username,
  "password"       -> password,
  "queryCustom"    -> createTableQueryString
))

```

**Comment by jarandaf** [comment]
I faced the same issue. You need to import `import com.microsoft.azure.sqldb.spark.query._` since the `azurePushdownQuery` is defined via implicit conversion.

**Comment by Axxeption** [comment]
I face the same issue even if I import "import com.microsoft.azure.sqldb.spark.query._"? I use Azure Databricks 5.4 with Apache Spark 2.4.3 and Scala 2.11 . All hints are welcome!

**Comment by david-nguyen** [comment]
The readme is straight-up wrong, the command should be `sqlDBQuery` instead of push down:

https://github.com/MicrosoftDocs/azure-docs/issues/14640

**Comment by B4PJS** [comment]
@Axxeption I used `sqlContext.sqlDBQuery(config)` to issue a pushdown query instead

**Comment by arvindshmicrosoft** [comment]
The option presented by @B4PJS is the correct way to address this. Closing the issue.
