### ISSUE TITLE
Session stays open even after bulk insert compeletes

### ISSUE THREAD

**Issue by dilkushpatel** [Azure/azure-sqldb-spark#36]
What I observe is spid opened for data insert stays alive for days after data load completes when using bulk load, as a result when someone tries running select it gets stuck with blk by spid of bulk insert job.
I needed can provide screenshots of same

code:

val bulkCopyConfig = Config(Map(
  "url"               -> "servername.eastus.cloudapp.azure.com",
  "port"              -> "1",
  "databaseName"      -> "PPPP",
  "user"              -> "vvvvv",
  "password"          -> "Password",
  "databaseName"      -> "P360",
  "dbTable"           -> tablename,
  "bulkCopyBatchSize" -> "50000",
  "bulkCopyTableLock" -> "true",
  "bulkCopyTimeout"   -> "600"
))

data.bulkCopyToSqlDB(bulkCopyConfig)

**Comment by arvindshmicrosoft** [comment]
As you would have noticed, this project is not being actively maintained. Instead, [Apache Spark Connector for SQL Server and Azure SQL](https://github.com/microsoft/sql-spark-connector) is now available, with support for Python and R bindings, an easier-to use interface to bulk insert data, and many other improvements. This repo will soon be archived (set to read-only). We encourage you to actively evaluate and use the new connector.

Unfortunately, this is a known issue which we have no plans to fix in this connector. Please check if you see similar issues with the newer connector and we can address it in that one.
