### ISSUE TITLE
com.microsoft.sqlserver.jdbc.SQLServerException: Cannot find data type 'TEXT'.

### ISSUE THREAD

**Issue by rajeshmese** [Azure/azure-sqldb-spark#39]
I'm trying read data from csv and load to AZURE SQLDW db. But getting the below error while using save mode overwrite or when table not exists.

Exception in thread "main" com.microsoft.sqlserver.jdbc.SQLServerException: Cannot find data type 'TEXT'.
        at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:259)
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1547)

Please help in resolving it.

**Comment by gjeevanm** [comment]
Need to override getJDBCType() method  and provide implementation for StringType accordingly . You can refer below 

https://github.com/gjeevanm/SparkADWWriter/blob/master/src/main/scala/sample/ADWWriteHelper.scala

**Comment by arvindshmicrosoft** [comment]
Thank you @gjeevanm for your help! I hope it helped @rajeshmese . In any case, there are two important points:
1. If you are using Azure Databricks, please consider using the [specialized DW connector](https://docs.microsoft.com/en-us/azure/databricks/scenarios/databricks-extract-load-sql-data-warehouse#load-data-into-azure-synapse)
2. This project is not actively maintained. Please see #95 for related guidance.
