### ISSUE TITLE
 expected but string literal found

### ISSUE THREAD

**Issue by sneevand** [Azure/azure-sqldb-spark#40]
import com.microsoft.azure.sqldb.spark.config.Config
import com.microsoft.azure.sqldb.spark.connect._

val config = Config(Map(
  "url"            -> "10.12.14.15",
  "databaseName"   -> "AdventureWorks",
  "dbTable"        -> "dbo.Employee"
  "user"           -> "nnn",
  "password"       -> "nn",
  "connectTimeout" -> "5", //seconds
  "queryTimeout"   -> "5"  //seconds
))
val collection = sqlContext.read.sqlDB(config)
collection.show()

Got Below error:
<console>:12: error: ')' expected but string literal found.
  "user"           -> "nnn",
  ^

![image](https://user-images.githubusercontent.com/13268402/60205491-ef1f0200-9816-11e9-8a16-f6a5514d3649.png)

**Comment by InterruptSpeed** [comment]
i think there is a comma missing after dbo.Employee". should be:
```
val config = Config(Map(
"url" -> "10.12.14.15",
"databaseName" -> "AdventureWorks",
"dbTable" -> "dbo.Employee",
"user" -> "nnn",
"password" -> "nn",
"connectTimeout" -> "5", //seconds
"queryTimeout" -> "5" //seconds
))
```

**Comment by arvindshmicrosoft** [comment]
The hint from @InterruptSpeed presumably has helped, thank you.

Closing this issue due to subsequent inactivity.
