### ISSUE TITLE
Bulk Insert not working for Datetime datatype in ASDW

### ISSUE THREAD

**Issue by jymbo** [Azure/azure-sqldb-spark#41]
There appears to be an issue when attempting to bulk insert into an azure sql data warehouse table that has a datetime datatype. The originating datatype in databricks is timestamp, which should be compatible with datetime. However; I get this error every time: 

`SqlNativeBufferBufferBulkCopy.WriteTdsDataToServer, error in OdbcDone: SqlState: 42000, NativeError: 4816, 'Error calling: bcp_done(this->GetHdbc()) | SQL Error Info: SrvrMsgState: 1, SrvrSeverity: 16,  Error <1>: ErrorMsg: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column type from bcp client for colid 2. | Error calling: pConn->Done() | state: FFFF, number: 233925, active connections: 5', Connection String: Driver={pdwodbc17e};app=TypeC01-DmsNativeWriter:DB66\mpdwsvc (13056)-ODBC;trusted_connection=yes;autotranslate=no;server=\\.\pipe\DB.66-a313018f1e5b\sql\query;database=Distribution_9`

When changing the target datatype from a datetime to a varchar, it bulk inserts just fine.

**Comment by saumyasuhagiya** [comment]
I am also facing the same!

**Comment by rodrigofp-cit** [comment]
Me too

**Comment by btafel** [comment]
did anyone find a solution to this?

**Comment by FlavioDiasPs** [comment]
I am facing it too

**Comment by dimitri-b** [comment]
I'm getting the same error. Disappears when loading as varchar.

**Comment by arvindshmicrosoft** [comment]
Sorry, this connector was never tested rigorously with Azure SQL DW (now Azure Synapse Analytics). Instead, for Databricks use cases we recommend using the [DW specific connector](https://docs.microsoft.com/en-us/azure/databricks/scenarios/databricks-extract-load-sql-data-warehouse#load-data-into-azure-synapse) instead.

Also, please note that this project is not actively maintained. I strongly recommend evaluating the DW-specific connector as mentioned above. Closing this issue.
