### ISSUE TITLE
Enhancement : Not compatible with spark session object

### ISSUE THREAD

**Issue by poojankothari-gep** [Azure/azure-sqldb-spark#45]
Cannot use APIs with Spark Session object.
Hence to use it i have to forcibly create SQL context object

**Comment by arvindshmicrosoft** [comment]
Thank you @poojankothari-gep . Unfortunately, this connector is not actively maintained. I recommend you evaluate and hopefully adopt the [newer connector](https://github.com/microsoft/sql-spark-connector) which is active. Closing this issue.
