### ISSUE TITLE
[Question] Is there any way to use a full connection string to connect?

### ISSUE THREAD

**Issue by david-nguyen** [Azure/azure-sqldb-spark#46]
As titled, the intent is to have one secret in our key vault to pass through a connection string to the JDBC connection.

**Comment by InterruptSpeed** [comment]
as an idea you could have a json string like this one in your keyvault:
```
{"connectTimeout" : "5", "url" : "<resourcename>.database.windows.net", "bulkCopyTimeout" : "6000", "bulkCopyTableLock" : "true", "databaseName" : "dbname", "bulkCopyBatchSize" : "100000", "user" : "username_credential", "password" : "password_credential"}
```
and then pull it out of keyvault and use it like this:
```
// Import libraries
import com.microsoft.azure.sqldb.spark.config.Config
import com.microsoft.azure.sqldb.spark.connect._
import org.apache.spark.sql.functions._

// pull string out of keyvault and assign to final val jsonStr, then:
val m = scala.util.parsing.json.JSON.parseFull(jsonStr).getOrElse(0).asInstanceOf[scala.collection.Map[String,String]] + ("dbTable" -> "tbl_details") // change dbTable value to your target table

val writeConfig = Config(m)

// load dataframe here

df.bulkCopyToSqlDB(writeConfig)
```

where in the above you could manage the batch size and timeout in the same way you manage the target table.

apologies if i misunderstood the question.

**Comment by david-nguyen** [comment]
Interesting I guess I could do that - I was hoping I could pull the connection string in ci/cd and store that in a secret but this might be a plan of attack

**Comment by InterruptSpeed** [comment]
there might be a better way to do it via ci/cd; this was just an approach. if you land on a better on i'd be keen to trade secrets. :)
