### ISSUE TITLE
ActiveDirectoryIntegrated option is not working

### ISSUE THREAD

**Issue by sara85sara** [Azure/azure-sqldb-spark#50]
this document only giving example of ActiveDirectoryPassword. How to connect with ActiveDirectoryIntegrated authentication 

https://docs.microsoft.com/en-us/azure/sql-database/sql-database-spark-connector

**Comment by arvindshmicrosoft** [comment]
This project is not actively maintained, and ActiveDirectoryIntegrated was not in scope. There is a [newer connector](https://github.com/microsoft/sql-spark-connector) which supports Windows Authentication as well, which might help you - please evaluate and hopefully adopt that connector.
