### ISSUE TITLE
This does not work for datetime columns

### ISSUE THREAD

**Issue by FlavioDiasPs** [Azure/azure-sqldb-spark#56]
I am receiving the error below no matter what I do:

`SqlNativeBufferBufferBulkCopy.WriteTdsDataToServer, error in OdbcDone: SqlState: 42000, NativeError: 4816, 'Error calling: bcp_done(this->GetHdbc()) | SQL Error Info: SrvrMsgState: 1, SrvrSeverity: 16,  Error <1>: ErrorMsg: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column type from bcp client for colid 8. | Error calling: pConn->Done() ...`

**Comment by giogaruffi** [comment]
https://docs.microsoft.com/en-us/sql/connect/jdbc/use-bulk-copy-api-batch-insert-operation?view=sql-server-ver15#known-limitations

**Comment by arvindshmicrosoft** [comment]
Thank you @giogaruffi for the related link.. Also, this project is not actively maintained - please see #95 for details. Hence, closing.
