### ISSUE TITLE
Error: Modules were resolved with conflicting cross-version suffixes in ProjectRef

### ISSUE THREAD

**Issue by sudarjs** [Azure/azure-sqldb-spark#62]
scalaVersion := "2.12.10"

// https://mvnrepository.com/artifact/org.apache.spark/spark-core
libraryDependencies += "org.apache.spark" %% "spark-core" % "2.4.5" % "provided"

// https://mvnrepository.com/artifact/com.microsoft.azure/azure-sqldb-spark
libraryDependencies += "com.microsoft.azure" % "azure-sqldb-spark" % "1.0.2"

**Comment by Fokko** [comment]
We had similar issues because of coalisions between Spark 2.2.2 and 2.4.5. PR https://github.com/Azure/azure-sqldb-spark/pull/70 fixes this by making it not part of the jar.

**Comment by arvindshmicrosoft** [comment]
Thank you @Fokko for the help! Closing this issue as no action is expected, nor is likely given the non-maintained state of this repo.
