### ISSUE TITLE
No examples showing SQL in Azure Databricks

### ISSUE THREAD

**Issue by ezra-at-lumedic** [Azure/azure-sqldb-spark#65]
Please include samples or examples of using the driver from SQL in Azure Databricks and not only in Scala.

In particular: what is the name of the JDBC Driver class?

**Comment by arvindshmicrosoft** [comment]
This connector is Scala-only. Consider evaluating the 
[Apache Spark Connector for SQL Server and Azure SQL](https://github.com/microsoft/sql-spark-connector) which is a newer connector. It adds support for Python and R bindings, amongst other improvements.
