### ISSUE TITLE
Ability to perform a merge

### ISSUE THREAD

**Issue by ttelfer** [Azure/azure-sqldb-spark#7]
It would be helpful for some work types to have the ability to perform a merge. We are currently using the Azure Databricks Delta to do merge, but it would be helpful if we could do the same to our Azure SQL Server instance and then utilize indexes.

**Comment by aravish** [comment]
Is MERGE supported with this connector? We could only find append option collection.write.mode(SaveMode.Append).sqlDB(config)

**Comment by arvindshmicrosoft** [comment]
Out of scope for this connector. Instead, consider post-processing the staging table (which was bulk loaded into) with a MERGE into the final table.
