### ISSUE TITLE
Scala 2.12 support

### ISSUE THREAD

**Issue by Samuman93** [Azure/azure-sqldb-spark#73]
Do you plan to add support to scala version 2.12?

**Comment by arvindshmicrosoft** [comment]
Thank you for your questions and ideas. There are no plans for Scala 2.12 with this connector. Consider evaluating the 
[Apache Spark Connector for SQL Server and Azure SQL](https://github.com/microsoft/sql-spark-connector) which is a newer connector, where Scala 2.12 may already work, or you can raise an issue in that repo to request it. I am closing this issue as there are no plans to address this request in this connector.
