### ISSUE TITLE
facing issues while read data from sql using azure-sqldb-spark 1.0.2...please help

### ISSUE THREAD

**Issue by krishjun20** [Azure/azure-sqldb-spark#77]
Hi Team,  Facing issues while connect to azure sql for read data using scala(maven platform)and used packages azure-sqldb-spark 1.0.2,adal4j 1.2.0 and mssql-jdbc 7.4.0.jre8 . Please heck below exception details... Please help.
Code :
 val config = Config(Map(
      "url" -> "*****.database.windows.net",
      "databaseName" -> "dbanme",
      "user" -> "userid",
      "password" -> "********",
      "queryCustom" -> query
    ))

      println(s"SQL Query: ${config.properties.get("queryCustom")}")
      resultDF = sparkSession.sqlContext.read.sqlDB(config)
      resultDF.show()
      )

Error:
Exception in thread "main" java.lang.NoClassDefFoundError: com/microsoft/azure/sqldb/spark/config/Config$...

**Comment by arvindshmicrosoft** [comment]
Thank you for using the connector. Have you verified that the JAR is on the classpath? What Spark platform are you using (Databricks / HDInsight / something else)?

**Comment by arvindshmicrosoft** [comment]
Closing due to lack of response.
