### ISSUE TITLE
There is no method to increase the adal token expiry time

### ISSUE THREAD

**Issue by BhaskarDasari** [Azure/azure-sqldb-spark#79]
Currently getExpiresAfter() method of adal4j.authenticationresult doesnt have method to increase the token expiry time from 60 minutes. This issue currently lets the long running data copy fails after 60 minutes.

val expireAfter = authResult.get().getExpiresAfter

https://docs.microsoft.com/en-us/java/api/com.microsoft.aad.adal4j.authenticationresult?view=azure-java-stable

**Comment by arvindshmicrosoft** [comment]
Unfortunately, this is not an issue we can address in this project. It appears to be specific to ADAL4J, which itself is not being actively maintained as per [their repo](https://github.com/AzureAD/azure-activedirectory-library-for-java). You could try posting to their Issues page, or consult other resources in the hope of finding some way forward. Sorry, we could not help! Closing this issue.
