### ISSUE TITLE
SQLServerException - connections pending at sql server side and spark session keep running

### ISSUE THREAD

**Issue by xiaoxiao-24** [Azure/azure-sqldb-spark#82]
I'am using the bulk insert, to test a scenario when "bulkCopyTimeout" is not long enough if Spark Connector can throw the exception and close the connection correctly.

result:

at Spark: 
the job is running (waiting for SQL Server ), in the log we see that exception is thrown with message:  "SQLServerException, An error occurred while writing to database, attempting rollback" 

at SQL Server 
connections are kept open with status "sleeping".

**Comment by arvindshmicrosoft** [comment]
As you would have noticed, this project is not being actively maintained. Instead, [Apache Spark Connector for SQL Server and Azure SQL](https://github.com/microsoft/sql-spark-connector) is now available, with support for Python and R bindings, an easier-to use interface to bulk insert data, and many other improvements. This repo will soon be archived (set to read-only). We encourage you to actively evaluate and use the new connector.

Unfortunately, this is a known issue which we have no plans to fix in this connector. Please check if you see similar issues with the newer connector and we can address it in that one.
