### ISSUE TITLE
bulkCopyToSqlDB is not working in Spark 3.0

### ISSUE THREAD

**Issue by shrwan5** [Azure/azure-sqldb-spark#85]
bulkCopyToSqlDB stopped working when upgraded to spark 3.0

**Comment by furlong46** [comment]
Same issue here

**Comment by arvindshmicrosoft** [comment]
This library is no longer actively maintained. The newer connector mentioned in the linked issue #95 has open PRs to add Spark 3.0 support. Please follow the work there and thank you for your understanding. Closing this issue as it will not be addressed in this repo / library.
