### ISSUE TITLE
azure-sqldb-spark-bulk-copy-insert-duplicate-rows

### ISSUE THREAD

**Issue by 102596** [Azure/azure-sqldb-spark#87]
Hi Team,

I have been using the spark-bulk-copy to transfer the data from databricks delta table into a table in the azure sql database.

I am noticing there were duplicate rows records inserted into the table in azure sql database intermittently.
for example,
Delta table     :  1200 rows
Azuresqltable :  2400 rows

This issue only happened intermittently, once i re-run the job. everything looks good. and i have confirmed that the delta table does not have the duplicate rows at all. so it might be an issue when pushing the data from delta table into the azure table via spark bulk copy.

---This is my partial code---

val bulkCopyConfig = Config(Map(
  "url"               -> HostName,
  "databaseName"      -> deltatargetdbname,
  "user"              -> jdbcUsername,
  "password"          -> jdbcPassword,
  "dbTable"           -> pushquerytablename ,
  "bulkCopyBatchSize" -> "5000",
  "bulkCopyTableLock" -> "true",
  "bulkCopyTimeout"   -> "1800"
))

df.bulkCopyToSqlDB(bulkCopyConfig)

**Comment by arvindshmicrosoft** [comment]
My understanding is that this is a possible boundary condition which might occur if any Spark executor retries execution just a bit after the internal SQL bulk copy operation completed its work. The newer connector [here](https://github.com/microsoft/sql-spark-connector) has a `NO_DUPLICATES` mode of operation which is specifically targeted at this scenario. We strongly recommend you to evaluate and adopt the new connector as this current repo is not maintained actively. Thank you for your understanding.
