### ISSUE TITLE
Clarification on exactly-once guarantee

### ISSUE THREAD

**Issue by jdocampo** [Azure/azure-sqldb-spark#90]
Hi,

Seeing the docs, its not exactly clear if the single and bulk modes support exactly once guarantees when appending to a table.
Could you clarify if it is possible to achieve this (I'm specially interested in the bulk scenario), and if any specific configuration is needed to achieve it?

**Comment by arvindshmicrosoft** [comment]
This connector does not offer such a guarantee. The [newer connector](https://github.com/microsoft/sql-spark-connector/) does offer a `NO_DUPLICATES` mode which you are looking for.

Closing this issue as there are no plans to further develop this connector.
